import { CalendarDays, Clock3, MapPin, Ticket } from "lucide-react";
import type { StructuredUI } from "@/types/glocal";

const date = new Intl.DateTimeFormat("es-MX", { weekday: "short", day: "numeric", month: "short", hour: "numeric", minute: "2-digit" });
export function EventMiniCard({ event }: { event: Extract<StructuredUI, { type: "event_card" }>["event"] }) { return <article className={`event-gradient ${event.heroImage} overflow-hidden rounded-2xl border border-white/10 p-4`}><div className="mb-12 flex gap-2">{event.tags.map((tag) => <span key={tag} className="rounded-full bg-black/30 px-2.5 py-1 text-[10px] font-bold uppercase tracking-widest text-white/80">{tag}</span>)}</div><h4 className="text-lg font-semibold text-white">{event.name}</h4><p className="mt-2 flex items-center gap-2 text-xs text-white/70"><MapPin size={13} />{event.venue.name}, {event.city}</p><p className="mt-1 flex items-center gap-2 text-xs text-white/70"><CalendarDays size={13} />{date.format(new Date(event.startDate))}</p></article> }

export function StructuredBlock({ block, onCheckout }: { block: StructuredUI; onCheckout: (checkout: Extract<StructuredUI, { type: "checkout" }>) => void }) {
  if (block.type === "event_card") return <EventMiniCard event={block.event} />;
  if (block.type === "event_list") return <div className="grid gap-2">{block.events.map((event) => <EventMiniCard key={event.id} event={event} />)}</div>;
  if (block.type === "lineup") return <div className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.2em] text-lime-300">Lineup confirmado</p>{block.lineup.map((item) => <div key={item.artist.id} className="flex items-center justify-between border-t border-white/10 py-3 first:border-0"><div><p className="font-semibold text-white">{item.artist.name}</p><p className="text-xs text-white/45">{item.stage}</p></div><span className="flex items-center gap-1 text-xs text-white/60"><Clock3 size={12} />{new Date(item.performanceTime).toLocaleTimeString("es-MX", { hour: "numeric", minute: "2-digit" })}</span></div>)}</div>;
  if (block.type === "ticket_options") return <div className="space-y-2">{block.tickets.map((ticket) => <div key={ticket.id} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[.04] p-3"><div><p className="font-semibold text-white">{ticket.name}</p><p className="text-[11px] text-white/45">{ticket.description}</p></div><div className="text-right"><p className="font-semibold text-lime-300">{ticket.priceDisplay}</p><p className="text-[10px] uppercase text-white/40">{ticket.availability === "low" ? "Pocos" : "Disponible"}</p></div></div>)}</div>;
  const isMock = block.providerId === "mock";
  return <div className="overflow-hidden rounded-2xl border border-lime-300/25 bg-lime-300/[.06] p-4"><div className="flex items-center gap-2 text-lime-300"><Ticket size={16} /><span className="text-[10px] font-bold uppercase tracking-[.2em]">Acceso listo</span></div><div className="my-4 flex items-end justify-between"><div><p className="text-xl font-semibold text-white">{block.quantity} × {block.ticketName}</p><p className="text-xs text-white/50">{block.eventName}</p></div><p className="text-xl font-semibold text-white">${block.total.toLocaleString("es-MX")} <span className="text-xs text-white/45">{block.currency}</span></p></div><button type="button" onClick={() => onCheckout(block)} className="w-full rounded-xl bg-lime-300 px-4 py-3 text-sm font-bold text-neutral-950 transition hover:bg-lime-200">{isMock ? "Comprar accesos" : "Pagar con Mercado Pago"}</button><p className="mt-2 text-center text-[10px] text-white/35">{isMock ? "Checkout simulado · No se procesará ningún pago" : "Serás redirigido al entorno seguro de Mercado Pago"}</p></div>;
}
