create extension if not exists pgcrypto;
create table organizers (id uuid primary key default gen_random_uuid(), name text not null, type text, website text, email text, phone text, created_at timestamptz not null default now());
create table venues (id uuid primary key default gen_random_uuid(), name text not null, address text, city text not null, state text, country text not null, latitude numeric(9,6), longitude numeric(9,6), capacity integer check (capacity >= 0));
create table events (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text, short_description text, category text not null, status text not null check (status in ('draft','published','cancelled')), start_date timestamptz not null, end_date timestamptz not null, venue_id uuid references venues(id), city text not null, state text, country text not null, hero_image text, organizer_id uuid references organizers(id), ticketing_provider text not null, external_event_id text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (end_date > start_date));
create table artists (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, description text, image text, external_reference text);
create table event_artists (event_id uuid references events(id) on delete cascade, artist_id uuid references artists(id) on delete cascade, stage text, performance_time timestamptz, position integer, primary key (event_id, artist_id));
create table ticket_types (id uuid primary key default gen_random_uuid(), event_id uuid references events(id) on delete cascade, name text not null, description text, price_display text not null, currency char(3) not null, external_ticket_type_id text, ticketing_provider text not null, status text not null, created_at timestamptz not null default now());
create index events_discovery_idx on events(status, city, start_date);
create index ticket_types_event_idx on ticket_types(event_id);
